name: Build and Push Docker Image

on:
  push:
    branches: [main]
    tags:
      - "*"

jobs:
  build-and-push:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_SECRET }}

      - name: Extract tag name
        id: tag_name
        run: echo "::set-output name=TAG::${GITHUB_REF#refs/tags/}"

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./src/.
          file: ./src/Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/cron-python:latest, ${{ secrets.REGISTRY_URL }}/cron-python:${{ steps.tag_name.outputs.TAG }}
          platforms: linux/amd64,linux/arm64
